site_name: Harvester - Open Source Hyperconverged Infrastructure
repo_url: https://github.com/harvester/harvester
edit_uri: https://github.com/harvester/docs/edit/main/docs/
# Set to false for local docs development
strict: true
theme:
  name: material
  palette:
    primary: green
  logo: 'assets/logo_horizontal_white.png'
  favicon: 'assets/favicon.ico'
  icon:
    repo: fontawesome/brands/github
#google_analytics:
extra:
  homepage: https://harvesterhci.io
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  #- markdownextradata: {}
markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true
nav:
  - index.md
  - Installation:
    - install/iso-install.md
    - install/pxe-boot-install.md
    - install/harvester-configuration.md
  - authentication.md
  - upgrade.md
  - harvester-network.md
  - import-image.md
  - VM Management:
    - vm/create-vm.md
    - vm/access-to-the-vm.md
    - vm/backup-restore.md
    - vm/live-migration.md
  - Rancher Integration:
    - rancher/rancher-integration.md
    - rancher/node-driver.md
  - Development:
    - dev/dev-mode.md
